### ISSUE TITLE
building and testing services section ext1

### ISSUE THREAD

**Issue by NC0312** [NC0312/social-it-up#1]
![test 1](https://github.com/user-attachments/assets/f89f625f-3d7e-4379-a0d9-c9b14c1ba33c)

test this section under the image section of services do check it for desktop as well as mobile view...

**Comment by NC0312** [comment]
@Jatin-1111 this section is under development will inform you once it's done

**Comment by NC0312** [comment]
@Jatin-1111 code is pushed kindly test

**Comment by Jatin-1111** [comment]
Working fine

**Comment by Jatin-1111** [comment]
Working fine
