### ISSUE TITLE
Change the alignment of fliters at admin panel 

### ISSUE THREAD

**Issue by NC0312** [NC0312/social-it-up#4]
Please make the alignment of filters at admin panel 
![image](https://github.com/user-attachments/assets/7f94b612-8d97-4373-8347-97b1de574fb7)

same as the bug panel
![image](https://github.com/user-attachments/assets/52151bef-b801-494d-9285-09a92df80e3a)

Note - These changes must be applicable only for desktop view for mobile view it should remain same as of now.

**Comment by Jatin-1111** [comment]
Done! from my side
